name: Updating and restarting the bot

on: 
  push:
    branches: [ main ]
    
jobs:
  ssh:
    name: Remote SSH Pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull the latest commits
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}

        script: ${{ secrets.SCRIPT }}
