name: Remote SSH Pull

on: 
  push:
    branches: [ main ]
    
jobs:
  ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pulling the latest commits via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ${{ secrets.SCRIPT }}
